作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [2]:
import numpy as np

In [18]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
a = array1.reshape(5, 6).ravel(order='F')
a

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [27]:
#2.呈上題的array，找出被6除餘1的數的索引
b = (a-1)/6 
b

array([-0.16666667,  0.83333333,  1.83333333,  2.83333333,  3.83333333,
        0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        0.16666667,  1.16666667,  2.16666667,  3.16666667,  4.16666667,
        0.33333333,  1.33333333,  2.33333333,  3.33333333,  4.33333333,
        0.5       ,  1.5       ,  2.5       ,  3.5       ,  4.5       ,
        0.66666667,  1.66666667,  2.66666667,  3.66666667,  4.66666667])

In [28]:
c = b.astype(int)
c

array([0, 0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4])

In [29]:
d = b-c
d

array([-0.16666667,  0.83333333,  0.83333333,  0.83333333,  0.83333333,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.5       ,  0.5       ,  0.5       ,  0.5       ,  0.5       ,
        0.66666667,  0.66666667,  0.66666667,  0.66666667,  0.66666667])

In [30]:
np.where(d==0)

(array([5, 6, 7, 8, 9], dtype=int64),)